Requiring **contiguous** 1D arrays for Cython functions.
When updating the `curve-curve-intersection` doc, I discovered
a bug:

    >>> import numpy as np
    >>> import bezier
    >>> nodes = np.asfortranarray([
    ...     [0.0, 1.0],
    ... ])
    >>> curve = bezier.Curve.from_nodes(nodes)
    >>> some_vals = np.asfortranarray([
    ...     [0.25, 0.75],
    ...     [0.25, 0.75],
    ... ])
    >>> s_vals = some_vals[0, :]
    >>> s_vals.base is some_vals
    True
    >>> s_vals
    array([0.25, 0.75])
    >>> s_vals.flags
      C_CONTIGUOUS : False
      F_CONTIGUOUS : False
      OWNDATA : False
      WRITEABLE : True
      ALIGNED : True
      WRITEBACKIFCOPY : False
      UPDATEIFCOPY : False
    >>> curve.evaluate_multi(s_vals)
    array([[0.25, 0.25]])
    >>> curve.evaluate(s_vals[0])
    array([[0.25]])
    >>> curve.evaluate(s_vals[1])
    array([[0.75]])

With the changes in this PR, this becomes:

    >>> curve.evaluate_multi(s_vals)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File ".../bezier/curve.py", line 242, in evaluate_multi
        return _curve_helpers.evaluate_multi(self._nodes, s_vals)
      File ".../bezier/_speedup.pyx", line 112, in bezier._speedup.evaluate_multi
        double[::1, :] nodes, double[::1] s_vals):
      File "stringsource", line 646, in View.MemoryView.memoryview_cwrapper
      File "stringsource", line 347, in View.MemoryView.memoryview.__cinit__
    ValueError: ndarray is not C-contiguous